export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_REQUEST_SUCCESS = 'PRODUCTS_REQUEST_SUCCESS';
export const PRODUCTS_REQUEST_FAILURE = 'PRODUCTS_REQUEST_FAILURE';

export const ADD_PRODUCT_TO_MY_CART = 'ADD_PRODUCT_TO_MY_CART';
export const REMOVE_PRODUCT_FROM_MY_CART = 'REMOVE_PRODUCT_FROM_MY_CART';
export const PROCEED_ALL_PRODUCTS = 'PROCEED_ALL_PRODUCTS';

export const USER_LOG_IN = 'USER_LOG_IN';
export const USER_LOG_OUT = 'USER_LOG_OUT';
