export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_REQUEST_SUCCESS = 'PRODUCTS_REQUEST_SUCCESS';
export const PRODUCTS_REQUEST_FAILURE = 'PRODUCTS_REQUEST_FAILURE';

export const ADD_PRODUCT_TO_MY_CART = 'ADD_PRODUCT_TO_MY_CART';
export const REMOVE_PRODUCT_FROM_MY_CART = 'REMOVE_PRODUCT_FROM_MY_CART';
export const REMOVE_ALL_PRODUCTS_FROM_MY_CART =
  'REMOVE_ALL_PRODUCTS_FROM_MY_CART';

export const USER_LOG_IN = 'USER_LOG_IN';
